### PR TITLE
Portfolio: mobile version

### PR DESCRIPTION
**Pull request by ogiogiovictor**
# Portfolio Project For Work Section and About Section.
**Main Changes** 
- Created the card sections with grid and flexbox
- Created the About me section with flexbox

### CODE REVIEW

**Review by MrRamoun — CHANGES_REQUESTED** [review]
# 🟠 Project Invalid! ⚓

## Hi @ogiogiovictor 👋

Unfortunately 😕, the project is *invalid* (that means I can not review it because you missed some rules that I have listed for you below ⬇️).

While you made a **really great** effort 💪 in this project that I really appreciate 🙇, unfortunately, _I cannot proceed to review your code_.

## Invalid Code Review Request

You have submitted a project, that has non-descriptive PR description

Your Code Review Request will be marked as **invalid** in your Dashboard. **Don't worry** though, You still have **3** More attepmts. So please submit a new one once you are ready 🙏.

> **Note:** In case you still have any questions or don't understand what is going on, please contact me at [Ramoun](#thank-you-for-your-time-🙏-and-call-me-if-you-need-help-or-clarification-☎️).
> **Note:** You can submit a new project by clicking on the **Submit Project** button in the **Dashboard**.

Cheers and Happy coding!👏👏👏

## Highlights 🌟

- x
- y
- z
- The code is top notch! 💯 and have a huge potential.

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. So, you can skip them if you don't have the time but remember to come back and implement them because they are going to enhance the quality of your code_

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [@ramoun16](https://twitter.com/ramoun16)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by ogiogiovictor** [comment]
Hi Ramon,

Can you help with the invalid sections, i don't understand

**Review by uche-inyama — CHANGES_REQUESTED** [review]
### Hi @ogiogiovictor :wave: 

## :dart: 
Your project is coming along just fine, especially the desktop version.

However, this submission is meant to assess the mobile version of the project, and the webpage does not respond correctly to mobile screen widths. Ensure your implementation of the mobile version of your portfolio is working properly.
  
If you think otherwise kindly reachout on slack, @Inyama Uchechukwu Henry, for clarifications.
### :slightly_smiling_face: 

## Required Changes ♻️

- [ ] The mobile version of the portfolio was not properly implemented.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ogiogiovictor** [comment]
Hi Inyama,

Can you specify what I need to adjust.

From my end I can see the mobile view just fine.

Kindly highlight what you want me to do

**Review by MrRamoun — APPROVED** [review]
# 🟢 Project Approved! 🏆

## Hi @ogiogiovictor 👋

Your project is complete! ✔️ 🏁. This is the First Project 1️⃣ You get Approved ✔️! in microverse 🌐.

Finally, **you did it**! 🎉 👏. Your code was very professional 💯 and I can see you have a great chance to be a Great Software Engineer ⛑️.

There is nothing else to say other than... _it's time to merge it_ :shipit:
Congratulations! 🎉. And Welcome to Microverse 👋.

> **Note:** You can now take a break even if short before you move on to the next project. Happy 😄 Coding 🖥️! and Have a nice day 🌞.

## Highlights 🌟

- ✔️ descriptive PR title and description
- ✔️ use git flow

## Optional suggestions 🤷‍♂️

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. So, you can skip them if you don't have the time but remember to come back and implement them because they are going to enhance the quality of your code_

You can also consider:

- [ ] [OPTIONAL] Try to use the same colors, padding, and margins as similar to the design as possible. 

BTW, Congrats 🎉 Again. Have a nice Weekend 😄.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **Twitter**: [@ramoun16](https://twitter.com/ramoun16)
- This is My **Slack**: [Ramoun](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request merged**
